### ISSUE TITLE
Failed to load about:blank

### ISSUE THREAD

**Issue by kclevenger** [walwe/md2pdf#5]
I get the following when running md2pdf [1]. 
It also does not include an image specified in the md [2].

[1]
$ md2pdf -c documents/stylesheets/markdown.css --keep-html -o out.pdf in.md
Loading page (1/2)
Warning: Blocked access to file
Error: Failed to load about:blank, with network status code 301 and http status code 0 - Protocol "about" is unknown
Printing pages (2/2)
Done
Exit with code 1 due to network error: ProtocolUnknownError

[2]
`<div width="100%" style="background-color:#EE0000;padding:25px;"><img src="image/logo.svg" height="80px"></div>`

**Comment by walwe** [comment]
This was introduced by a [wkthmltopdf change in version 0.12.6](https://github.com/mileszs/wicked_pdf/pull/920/commits).
Now local files are allowed as long as they are relative to the markdown file.

Fixed in [v0.0.5](https://github.com/walwe/md2pdf/releases/tag/v0.0.5)
